module.exports = {
    status: {
        playerName: '#player-name',
        realm: '#summary-realm-display',
        cultivation: '#summary-cultivation-display',
        lingshi: '#summary-lingshi-display',
        activePage: '.page.active',
    },
    tabs: {
        cultivation: '[data-tab="cultivation"]',
        story: '[data-tab="story"]',
        inventory: '[data-action="inventory"]',
        settings: '[data-action="settings"]',
    },
    pages: {
        cultivation: '.page[data-page="cultivation"]',
        story: '.page[data-page="story"]',
    },
    cultivation: {
        mainButton: '#main-btn',
        hint: '#hint-text',
        rate: '#breakthrough-inline',
        trainCost: '#train-cost-text',
        batchButton: (batchKey) => `[data-train-batch="${batchKey}"]`,
    },
    story: {
        title: '#story-title',
        line: '#story-line',
        progress: '#story-progress',
        continueButton: '#story-continue-btn',
        skipButton: '#story-skip-btn',
        choices: '#story-choices',
        pressure: '#story-pressure',
        endingChain: '#story-ending-chain',
        goal: '#story-goal',
        echoList: '#echo-list',
    },
    journey: {
        preview: '#combat-preview',
        locationTitle: '#location-title',
        locationDesc: '#location-desc',
        npcs: '#location-npcs',
        clues: '#side-story-list',
    },
    inventory: {
        modal: '#inventory-modal',
        closeButton: '#close-inventory',
        list: '#inventory-list',
        useButton: (itemId) => `[data-use-item="${itemId}"]`,
        actionButton: (itemId, actionId) => `[data-item-id="${itemId}"][data-item-action="${actionId}"]`,
        anyActionButton: (itemId) => `[data-item-id="${itemId}"][data-item-action]`,
    },
    settings: {
        modal: '#settings-modal',
        closeButton: '#close-settings',
        audioToggle: '#audio-toggle',
        musicToggle: '#music-toggle',
        exportButton: '#export-btn',
        importButton: '#import-btn',
        resetButton: '#reset-btn',
        confirmResetButton: '#confirm-reset',
        cancelResetButton: '#cancel-reset',
        saveModeNote: '#save-mode-note',
    },
    combat: {
        modal: '#combat-modal',
        title: '#combat-title',
        log: '#combat-log',
    },
};
